### ISSUE TITLE
Property value expected type of string but got null

### ISSUE THREAD

**Issue by jonatasfreitasv** [palantir/react-mosaic#70]
.js file

```
ERROR in ./app/containers/HomePage.js
Module build failed: TypeError: /home/anon/Projects/HouseOps/app/containers/HomePage.js: Property value expected type of string but got null
    at Object.validate (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/index.js:466:7)
    at converters.GenericTypeAnnotation (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:607:52)
    at convert (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:52:16)
    at converters.ObjectTypeIndexer (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:728:92)
    at convert (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:52:16)
    at /home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:693:12
    at Array.map (<anonymous>)
    at converters.ObjectTypeAnnotation (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:692:114)
 @ ./app/routes.js 17:16-48
 @ ./app/containers/Root.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.j
```

```js
// @flow
import React, { Component } from 'react';
import { Mosaic } from 'react-mosaic-component';

type Props = {};

export default class HomePage extends Component<Props> {
  props: Props;

  ELEMENT_MAP: { [viewId: string]: JSX.Element } = {
    a: <div>Left Window</div>,
    b: <div>Top Right Window</div>,
    c: <div>Bottom Right Window</div>,
  };

  openSettings = () => {
    // this.databaseConnConfiguration.handleOpen();
  };

  reload = () => {
    location.reload(true); // eslint-disable-line
  };

  render() {
    return (
      <Mosaic
        renderTile={(id) => this.ELEMENT_MAP[id]}
        initialValue={{
          direction: 'row',
          first: 'a',
          second: {
            direction: 'column',
            first: 'b',
            second: 'c',
          },
          splitPercentage: 40,
        }}
      />

    );
  }
}

```

**Comment by nomcopter** [comment]
Looks like a flow compilation problem with your usage of `react-mosaic`. The error does not give me enough information and I do not know flow. Happy to look into more if you give me an example repo with this problem.
