### ISSUE TITLE
Error in a simple implementation - Property value expected type of string but got null

### ISSUE THREAD

**Issue by jonatasfreitasv** [palantir/react-mosaic#71]
### Bug report

- __Package version(s)__: 1.1.1
- __Browser and OS versions__:  Ubuntu + Electron

In a Simple Tiling example with Electron + React.

Code and project is here:
https://github.com/HouseOps/HouseOps/blob/version-1.0.0-beta/app/containers/HomePage.js

Full stacktrace:

```
ERROR in ./app/containers/HomePage.js
Module build failed: TypeError: /home/anon/Projects/HouseOps/app/containers/HomePage.js: Property value expected type of string but got null
    at Object.validate (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/anon/Projects/HouseOps/node_modules/babel-types/lib/index.js:466:7)
    at converters.GenericTypeAnnotation (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:607:52)
    at convert (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:52:16)
    at converters.ObjectTypeIndexer (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:728:92)
    at convert (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:52:16)
    at /home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:693:12
    at Array.map (<anonymous>)
    at converters.ObjectTypeAnnotation (/home/anon/Projects/HouseOps/node_modules/babel-plugin-flow-runtime/lib/convert.js:692:114)
 @ ./app/routes.js 17:16-48
 @ ./app/containers/Root.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js
```

**Comment by nomcopter** [comment]
I'm not sure what is wrong with the flow typings in your project, but removing the type parameter on `ELEMENT_MAP` fixes it.

**Comment by jonatasfreitasv** [comment]
Not solve.

To solve I make this:

```
const ELEMENT_MAP: { [viewId: string]: any } = {
  a: <div>Left Window</div>,
  b: <div>Top Right Window</div>,
  c: <div>Bottom Right Window</div>,
};
```

**Comment by nomcopter** [comment]
Remove everything between the : and =
